AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'spec/template_spec.rb'



# definitive :
Style/ClassVars:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Style/MutableConstant:
  Enabled: false

# to study :

Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
